steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/your-diet-backend:$_REF_NAME', '.']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/your-diet-backend:$_REF_NAME']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--image'
      - 'gcr.io/$PROJECT_ID/your-diet-backend:$_REF_NAME'
      - '--region'
      - $_DEPLOY_REGION
      - '--platform'
      - $_PLATFORM
      - '--set-env-vars'
      - 'MONGODB_URL=$_MONGODB_URL,MONGO_DB_NAME=$_MONGO_DB_NAME'
    entrypoint: gcloud

images:
  - 'gcr.io/$PROJECT_ID/your-diet-backend:$_REF_NAME'

options:
  logging: CLOUD_LOGGING_ONLY