steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/your-diet', '.']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/your-diet']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--image'
      - 'gcr.io/$PROJECT_ID/your-diet'
      - '--region'
      - $_DEPLOY_REGION
      - '--platform'
      - $_PLATFORM
      - '--set-env-vars'
      - 'MONGODB_URL=$MONGODB_URL,MONGO_DB_NAME=$MONGO_DB_NAME,PORT=$PORT'
    entrypoint: gcloud

images:
  - 'gcr.io/$PROJECT_ID/your-diet'

options:
  logging: CLOUD_LOGGING_ONLY