steps:
  # Fetch the latest tag from GitHub
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git fetch --tags
        export TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo $TAG > /workspace/LATEST_TAG

  # Build the Docker image with the tag
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TAG=$(cat /workspace/LATEST_TAG)
        docker build -t gcr.io/$PROJECT_ID/your-diet-backend:$TAG .

  # Push the Docker image with the tag
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TAG=$(cat /workspace/LATEST_TAG)
        docker push gcr.io/$PROJECT_ID/your-diet-backend:$TAG

images:
  - 'gcr.io/$PROJECT_ID/your-diet-backend'

options:
  logging: CLOUD_LOGGING_ONLY