steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/your-diet-backend', '.']
    dir: 'your-diet/your-diet'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/your-diet-backend']

images:
  - 'gcr.io/$PROJECT_ID/your-diet-backend'

options:
  logging: CLOUD_LOGGING_ONLY