version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  # api:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - MONGODB_URI=mongodb://mongodb:27017
  #   depends_on:
  #     - mongodb
  #   restart: unless-stopped
  #   # Uncomment the following if you have a .env file
  #   # env_file:
  #   #   - .env

volumes:
  mongodb_data: